# Generated by Django 5.2.5 on 2025-08-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee', models.CharField(max_length=50)),
                ('invite_type', models.CharField(choices=[('IP', 'In-Person'), ('LS', 'Access to View Livestream')], max_length=12)),
            ],
        ),
    ]
