# Generated by Django 5.2.5 on 2025-08-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='invite_type',
            field=models.CharField(max_length=12),
        ),
    ]
